name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Send Adaptive Card to Team Webhook
        run: |
          curl -X POST 'https://prod-07.southeastasia.logic.azure.com:443/workflows/029725cc35ae492c935f0cb75a985ec6/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=iVpL_jZCCm_tz6GTaG43xbNPzKkdwhs8mAHbgIKrdTQ' \
          -H "Content-Type: application/json" \
          -d '{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.3",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "✅ CI Workflow Completed",
                      "weight": "Bolder",
                      "size": "Medium"
                    },
                    {
                      "type": "TextBlock",
                      "text": "This is a test message from GitHub Actions!",
                      "wrap": true
                    },
                    {
                      "type": "TextBlock",
                      "text": "Triggered on: main branch",
                      "isSubtle": true,
                      "spacing": "Small"
                    }
                  ]
                }
              }
            ]
          }'
